### ISSUE TITLE
GCP dependency in the openEO notebook?

### ISSUE THREAD

**Issue by sebastian-luna-valero** [c-scale-community/use-case-waterwatch#14]
Hi,

When running:

https://github.com/c-scale-community/use-case-waterwatch/blob/main/notebooks/openeo_waterwatch.ipynb

There is the cell

```python
# Get reservoirs from database
reservoir_dir: Path = out_dir / "reservoirs"

reservoirs: List[Reservoir] = Reservoir.from_gcp(reservoir_dir)
```

Is this expected?

Context: I would like to configure this repo for `binder`: [xref](https://github.com/c-scale-community/use-case-waterwatch/compare/binder?expand=1). Then make a new release so it's ingested via Zenodo.

**Comment by sebastian-luna-valero** [comment]
Hi Jaap,

Please try this instead:

https://replay.notebooks.egi.eu/v2/gh/c-scale-community/use-case-waterwatch/binder?labpath=notebooks%2Fopeneo_waterwatch.ipynb

**Comment by Jaapel** [comment]
I pushed a commit to fix this authentication issue, can you retry?

**Comment by sebastian-luna-valero** [comment]
I get now:

```bash
File /srv/conda/envs/notebook/lib/python3.9/site-packages/google/auth/credentials.py:223, in AnonymousCredentials.refresh(self, request)
    220 def refresh(self, request):
    221     """Raises :class:``InvalidOperation``, anonymous credentials cannot be
    222     refreshed."""
--> 223     raise exceptions.InvalidOperation("Anonymous credentials cannot be refreshed.")

InvalidOperation: Anonymous credentials cannot be refreshed.
```

**Comment by Jaapel** [comment]
I cleaned and tested it myself now, it should work now

**Comment by sebastian-luna-valero** [comment]
Sorry, I am getting now:

```python
FileNotFoundError: [Errno 2] No such file or directory: 'output/reservoirs/reservoirs-v1.0.dbf'
```

**Comment by Jaapel** [comment]
I created the `out_dir` now by default,

**Comment by sebastian-luna-valero** [comment]
Thanks!

I get this warning:

![image](https://github.com/c-scale-community/use-case-waterwatch/assets/5345517/4bf54618-6afb-450a-b6df-773b18a551bf)

And this error:

![image](https://github.com/c-scale-community/use-case-waterwatch/assets/5345517/5f7dc9fd-8f9e-4628-8605-af69233d836f)

**Comment by Jaapel** [comment]
Thanks!
Seems like some versions changed at your end, let's see where this changed. 1st warning seems an update to the collection of the global surface water dataset, also on my TODOs now.

**Comment by sebastian-luna-valero** [comment]
Thanks!

I used [conda-lock](https://conda.github.io/conda-lock/) to create a permanent environment:
https://github.com/c-scale-community/use-case-waterwatch/blob/binder/conda-linux-64.lock

I was planning to make the release with this permanent environment.

**Comment by Jaapel** [comment]
I fixed openEO to 0.22 now

**Comment by sebastian-luna-valero** [comment]
New report ;)

See error:

![image](https://github.com/c-scale-community/use-case-waterwatch/assets/5345517/ff49e75f-65b4-42f5-8839-a8fbc73aca1d)

Warning:

![image](https://github.com/c-scale-community/use-case-waterwatch/assets/5345517/ce7e275b-6a53-4b17-b88c-4aa03731d4ed)

Success?

![image](https://github.com/c-scale-community/use-case-waterwatch/assets/5345517/122c08b9-1a78-49ae-a896-d4c50c46f8a6)

**Comment by Jaapel** [comment]
About the proj error: https://github.com/Toblerity/Fiona/issues/849, seems something went wrong with conda + binder, that PROJ_LIB is not set correctly. I do not have this error locally.
The warning will stay, that is for the backend guys to solve, as I am not renaming any of these bands.
Success indeed if you get the timeseries + watermask images!

**Comment by sebastian-luna-valero** [comment]
I guess this one is the watermask images?

![image](https://github.com/c-scale-community/use-case-waterwatch/assets/5345517/3f7aea72-2256-48b3-92c8-42885d7f1e96)

**Comment by sebastian-luna-valero** [comment]
Are you happy with this?

Should we merge and make a release?

**Comment by Jaapel** [comment]
Yes it is looking good!
You can merge if you want!
